development:
  adapter: mysql2
  pool_adapter: mysql2
  database: zone
  encoding: utf8
  pool: 5
  username: root
  password: 
  host: localhost
  port: 3306
  reconnect: true

test:
  adapter: mysql2
  pool_adapter: mysql2
  database: zone_test
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: 127.0.0.1
  port: 33306
  reconnect: true
