name: RSpec - Unit Testing

on: [push]

env:
  SOURCE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-20.04
    services:
      # How to use Mysql
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify MySQL
        run: |
          sudo apt-get install -y build-essential python-dev nginx-extras pkg-config cmake libxrender1 libmysqlclient-dev ncurses-dev gettext flex bison autoconf binutils-doc redis-tools vim nfs-common jq bc
          mysql --host 127.0.0.1 --port 33306 -uroot -ppassword -e "SHOW GRANTS FOR 'root'@'localhost'"
          mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host 127.0.0.1 --port 33306 -uroot -ppassword mysql

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          ruby-version: 2.6.5 # Not needed with a .ruby-version file

      - name: Create DB
        env:
          RAILS_ENV: test
        run: |
          gem install bundler --version 1.17.3
          bundle install
          bin/rails db:setup

      - name: Run tests
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_KEY }}
          RAILS_ENV: test
        run: |
          bundle exec rspec

      - name: Run undercover
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_KEY }}
          RAILS_ENV: test
        run: |
          bundle exec undercover
          ruby -e "$(curl -s https://undercover-ci.com/uploader.rb)" -- --repo selva8822/zone --commit ${{ github.sha }} --lcov coverage/lcov/zone.lcov
